stages:
  - build
  - test
build:
  stage: build
  script:
    - echo "Building ...."
    - mkdir fidecoin
    - touch fidecoin/info.txt
  artifacts:
    paths:
      - fidecoin/
test:
  stage: test
  script:
    - echo "Testing ...."
    - test -f "fidecoin/info.txt"
