stages:
  - build
  - test
build:
  stage: build
  script:
    - echo "Building ...."
    - mkdir fidecoin
    - touch fidecoin/info.txt
  artifacts:
    paths:
      - fidecoin/
postman_tests:
  stage: test
  image: postman/newman_alpine33
  script:
    - echo "Testing ...."
    - newman --version
    - test -f "fidecoin/info.txt"
