stages:
  - build
  - test-and-package
maven-compile-doc:
  stage: build
  script:
    - ./mvnw compile -Dmaven.repo.local=$MAVEN_USER_HOME
    - ./mvnw javadoc:javadoc -Dmaven.repo.local=$MAVEN_USER_HOME
    - npm run compodoc
  artifacts:
    paths:
      - target/site/
      - documentation/
    expire_in: 7 day
